### ISSUE TITLE
"IsLowPriority"  need to be removed in SimplePolicy of NEO3

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-plugins#109]
"IsLowPriority"  need to be removed in SimplePolicy since Transcation.get_IsLowPrioriy() has been removed.

![image](https://user-images.githubusercontent.com/38493437/62124436-c8b02300-b2fc-11e9-81cf-767e429bc4a2.png)

**Comment by shargon** [comment]
Yes, must be removed

**Comment by vncoelho** [comment]
@shargon, `FilterForMemoryPool` is also know a native contract. I believe it could be direct in the core code.

**Comment by erikzhang** [comment]
The SimplePolicy plugin will be removed.
