### ISSUE TITLE
ApplicationLogs plugin return exception while installed in NEO3

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-plugins#113]
neo-cli return exception while ApplicationLogs plugin installed in NEO3.
![image](https://user-images.githubusercontent.com/38493437/62455927-f6d4ad80-b7a9-11e9-834a-03c82e059486.png)
![image](https://user-images.githubusercontent.com/38493437/62456078-3f8c6680-b7aa-11e9-977e-f22ba2752e3f.png)

**Comment by erikzhang** [comment]
@superboyiii I created a patch, please test it again with the new plugins.

**Comment by superboyiii** [comment]
![image](https://user-images.githubusercontent.com/38493437/62689836-24b23000-b9fe-11e9-834c-984126d9b275.png)
@erikzhang  Issue still exists.

**Comment by erikzhang** [comment]
@superboyiii Fixed.

**Comment by superboyiii** [comment]
Great! Works well now.
![image](https://user-images.githubusercontent.com/38493437/62692172-c0459f80-ba02-11e9-8d02-8feac9798d14.png)

**Comment by superboyiii** [comment]
@erikzhang @shargon Isn't able to find the ```fee``` in Applicationlog.

**Comment by erikzhang** [comment]
What do you mean?

**Comment by superboyiii** [comment]
@erikzhang  I mean ```sys_fee``` and ```net_fee```, I think they should be displayed in ApplicationLog. But since there will be many ```toAddress``` of ```fee`` receivers, maybe the ```toAddress``` can be set to "". If this is not necessary , at least, the gas consume number should equal ```sys_fee``` + ```net_fee```, otherwise customers will confused with where their fee has gone or why the consume number isn't not equal what I paid, especially exchanges.

**Comment by erikzhang** [comment]
You can get `sys_fee` and `net_fee` from the transaction. `ApplicationLogs` is to get the execution results.

**Comment by superboyiii** [comment]
OK, I'll close this issue.
