### ISSUE TITLE
RpcNep5Tracker doesn't work in NEO3

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-plugins#114]
RpcNep5Tracker doesn't work in NEO3. Several transactions was made in this address and it does have asset, but from '''getnep5balances''' and '''getnep5transfers''' sides.
![image](https://user-images.githubusercontent.com/38493437/62509814-3ac5c200-b83f-11e9-9b76-f561b770b9ad.png)
![image](https://user-images.githubusercontent.com/38493437/62510216-c5f38780-b840-11e9-9a95-00d5f8e2bb97.png)
![image](https://user-images.githubusercontent.com/38493437/62510237-d4da3a00-b840-11e9-9a8e-f75dda83bad0.png)

**Comment by shargon** [comment]
This plugin require UTXO so i think that should be refactored for neo3

**Comment by lock9** [comment]
Hello,
I will close this issue in favor of #116.
