### ISSUE TITLE
PostProcess() of RpcWallet plugin isn't loaded when using "invoke", "invokescript", "invokefunction"

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-plugins#115]
PostProcess() of RpcWallet plugin isn't loaded when using ```invoke```, ```invokescript```, ```invokefunction```, it goes to RpcServer.cs to look for these three methods although RpcWallet plugin is installed. Other method like ```sendtoaddress```, ```sendfrom``` works well since OnProcess() in RpcWallet.cs is loaded.
For example, ```invoke``` method isn't in RpcServer.cs so that json response shows “method not found”.
![image](https://user-images.githubusercontent.com/38493437/62695904-e6bb0900-ba09-11e9-82ec-9f3cb56f5cd9.png)
And when using ```invokefunction```, it goes to here, in Rpcserver.cs:
![image](https://user-images.githubusercontent.com/38493437/62696054-37cafd00-ba0a-11e9-944a-eae3ba2f68c9.png)

**Comment by superboyiii** [comment]
I find that‘s in PostProcess() of RpcWallet, and it's absolutely not loaded. OnProcess() is loaded in Rpcserver.
![image](https://user-images.githubusercontent.com/38493437/62697852-45828180-ba0e-11e9-94db-f8bd120147c9.png)

**Comment by erikzhang** [comment]
`invoke` is removed from NEO3. You need to use `invokefunction` or `invokescript`.
