### ISSUE TITLE
Update RpcNep5Tracker to work in NEO3

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-plugins#116]
This plugin depends on UTXO, it must be refactored to work with NEO 3

From @shargon:
https://github.com/neo-project/neo-plugins/issues/114#issuecomment-518576175

**Comment by shargon** [comment]
I need to review if this plugin use UTXO or don't

**Comment by erikzhang** [comment]
@neo-project/core Anyone is working on this?

**Comment by vncoelho** [comment]
It looks like you, @erikzhang, fast as a thunder bolt...aheuahuea
