### ISSUE TITLE
Null value on Attributes causes invokefunction RPC failed.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-plugins#120]
Null value on ```Attributes``` causes ```invokefunction``` RPC failed.
![image](https://user-images.githubusercontent.com/38493437/62926570-5c96ea00-bde7-11e9-9173-8e4c67adbcf1.png)
<img width="934" alt="image" src="https://user-images.githubusercontent.com/38493437/62926637-7d5f3f80-bde7-11e9-9712-07c60d9298c3.png">

**Comment by shargon** [comment]
I think that this doesn't happen with the last version of neo-3x, because null is converted 

https://github.com/neo-project/neo/blob/cf768c63a3e2c07cda839495f8b836223832c634/neo/Wallets/Wallet.cs#L296

**Comment by superboyiii** [comment]
@shargon Wait for your fixed neo-cli, and I'll test it.

**Comment by superboyiii** [comment]
Tested, it's been fixed now.
