### ISSUE TITLE
Application logs location

### ISSUE THREAD

**Issue by ksemaev** [neo-project/neo-plugins#121]
I have my `/home/neo` directory with this layout:

> -data  
>   -Chain_00746E41  
>   -SystemAssetBalanceData
> -neo-cli with content:
>   -Plugins 
>      -ApplicationLogs
>       -config.json
>      ApplicationLogs.dll
>      - RpcSystemAssetTracker
>      RpcSystemAssetTracker.dll
>   Akka.dll
>   Microsoft.AspNetCore.Connections.Abstractions.dll
>   Microsoft.AspNetCore.Hosting.Abstractions.dll
>   Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
>   Microsoft.AspNetCore.Hosting.dll
>   Microsoft.AspNetCore.Http.Abstractions.dll
>   Microsoft.AspNetCore.Http.Extensions.dll
>   Microsoft.AspNetCore.Http.Features.dll
>   Microsoft.AspNetCore.Http.dll
>   Microsoft.AspNetCore.ResponseCompression.dll
>   Microsoft.AspNetCore.Server.Kestrel.Core.dll
>   Microsoft.AspNetCore.Server.Kestrel.Https.dll
>   Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll
>   Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll
>   Microsoft.AspNetCore.Server.Kestrel.dll
>   Microsoft.AspNetCore.WebSockets.dll
>   Microsoft.AspNetCore.WebUtilities.dll
>   Microsoft.CSharp.dll
>   Microsoft.Data.Sqlite.dll
>   Microsoft.DotNet.PlatformAbstractions.dll
>   Microsoft.EntityFrameworkCore.Abstractions.dll
>   Microsoft.EntityFrameworkCore.Relational.dll
>   Microsoft.EntityFrameworkCore.Sqlite.dll
>   Microsoft.EntityFrameworkCore.dll
>   Microsoft.Extensions.Caching.Abstractions.dll
>   Microsoft.Extensions.Caching.Memory.dll
>   Microsoft.Extensions.Configuration.Abstractions.dll
>   Microsoft.Extensions.Configuration.Binder.dll
>   Microsoft.Extensions.Configuration.EnvironmentVariables.dll
>   Microsoft.Extensions.Configuration.FileExtensions.dll
>   Microsoft.Extensions.Configuration.Json.dll
>   Microsoft.Extensions.Configuration.dll
>   Microsoft.Extensions.DependencyInjection.Abstractions.dll
>   Microsoft.Extensions.DependencyInjection.dll
>   Microsoft.Extensions.DependencyModel.dll
>   Microsoft.Extensions.FileProviders.Abstractions.dll
>   Microsoft.Extensions.FileProviders.Physical.dll
>   Microsoft.Extensions.FileSystemGlobbing.dll
>   Microsoft.Extensions.Hosting.Abstractions.dll
>   Microsoft.Extensions.Logging.Abstractions.dll
>   Microsoft.Extensions.Logging.dll
>   Microsoft.Extensions.ObjectPool.dll
>   Microsoft.Extensions.Options.dll
>   Microsoft.Extensions.Primitives.dll
>   Microsoft.Net.Http.Headers.dll
>   Microsoft.VisualBasic.dll
>   Microsoft.Win32.Primitives.dll
>   Microsoft.Win32.Registry.dll
>   Neo.VM.dll
>   Neo.dll
>   Newtonsoft.Json.dll
>   Remotion.Linq.dll
>   SOS.NETCore.dll
>   SQLitePCLRaw.batteries_green.dll
>   SQLitePCLRaw.batteries_v2.dll
>   SQLitePCLRaw.core.dll
>   SQLitePCLRaw.provider.e_sqlite3.dll
>   System.AppContext.dll
>   System.Buffers.dll
>   System.Collections.Concurrent.dll
>   System.Collections.Immutable.dll
>   System.Collections.NonGeneric.dll
>   System.Collections.Specialized.dll
>   System.Collections.dll
>   System.ComponentModel.Annotations.dll
>   System.ComponentModel.DataAnnotations.dll
>   System.ComponentModel.EventBasedAsync.dll
>   System.ComponentModel.Primitives.dll
>   System.ComponentModel.TypeConverter.dll
>   System.ComponentModel.dll
>   System.Configuration.dll
>   System.Console.dll
>   System.Core.dll
>   System.Data.Common.dll
>   System.Data.dll
>   System.Diagnostics.Contracts.dll
>   System.Diagnostics.Debug.dll
>   System.Diagnostics.DiagnosticSource.dll
>   System.Diagnostics.EventLog.dll
>   System.Diagnostics.FileVersionInfo.dll
>   System.Diagnostics.Process.dll
>   System.Diagnostics.StackTrace.dll
>   System.Diagnostics.TextWriterTraceListener.dll
>   System.Diagnostics.Tools.dll
>   System.Diagnostics.TraceSource.dll
>   System.Diagnostics.Tracing.dll
>   System.Drawing.Primitives.dll
>   System.Drawing.dll
>   System.Dynamic.Runtime.dll
>   System.Globalization.Calendars.dll
>   System.Globalization.Extensions.dll
>   System.Globalization.Native.so
>   System.Globalization.dll
>   System.IO.Compression.Brotli.dll
>   System.IO.Compression.FileSystem.dll
>   System.IO.Compression.Native.a
>   System.IO.Compression.Native.so
>   System.IO.Compression.ZipFile.dll
>   System.IO.Compression.dll
>   System.IO.FileSystem.AccessControl.dll
>   System.IO.FileSystem.DriveInfo.dll
>   System.IO.FileSystem.Primitives.dll
>   System.IO.FileSystem.Watcher.dll
>   System.IO.FileSystem.dll
>   System.IO.IsolatedStorage.dll
>   System.IO.MemoryMappedFiles.dll
>   System.IO.Pipelines.dll
>   System.IO.Pipes.AccessControl.dll
>   System.IO.Pipes.dll
>   System.IO.UnmanagedMemoryStream.dll
>   System.IO.dll
>   System.Interactive.Async.dll
>   System.Linq.Expressions.dll
>   System.Linq.Parallel.dll
>   System.Linq.Queryable.dll
>   System.Linq.dll
>   System.Memory.dll
>   System.Native.a
>   System.Native.so
>   System.Net.Http.Native.a
>   System.Net.Http.Native.so
>   System.Net.Http.dll
>   System.Net.HttpListener.dll
>   System.Net.Mail.dll
>   System.Net.NameResolution.dll
>   System.Net.NetworkInformation.dll
>   System.Net.Ping.dll
>   System.Net.Primitives.dll
>   System.Net.Requests.dll
>   System.Net.Security.Native.a
>   System.Net.Security.Native.so
>   System.Net.Security.dll
>   System.Net.ServicePoint.dll
>   System.Net.Sockets.dll
>   System.Net.WebClient.dll
>   System.Net.WebHeaderCollection.dll
>   System.Net.WebProxy.dll
>   System.Net.WebSockets.Client.dll
>   System.Net.WebSockets.WebSocketProtocol.dll
>   System.Net.WebSockets.dll
>   System.Net.dll
>   System.Numerics.Vectors.dll
>   System.Numerics.dll
>   System.ObjectModel.dll
>   System.Private.CoreLib.dll
>   System.Private.DataContractSerialization.dll
>   System.Private.Uri.dll
>   System.Private.Xml.Linq.dll
>   System.Private.Xml.dll
>   System.Reflection.DispatchProxy.dll
>   System.Reflection.Emit.ILGeneration.dll
>   System.Reflection.Emit.Lightweight.dll
>   System.Reflection.Emit.dll
>   System.Reflection.Extensions.dll
>   System.Reflection.Metadata.dll
>   System.Reflection.Primitives.dll
>   System.Reflection.TypeExtensions.dll
>   System.Reflection.dll
>   System.Resources.Reader.dll
>   System.Resources.ResourceManager.dll
>   System.Resources.Writer.dll
>   System.Runtime.CompilerServices.Unsafe.dll
>   System.Runtime.CompilerServices.VisualC.dll
>   System.Runtime.Extensions.dll
>   System.Runtime.Handles.dll
>   System.Runtime.InteropServices.RuntimeInformation.dll
>   System.Runtime.InteropServices.WindowsRuntime.dll
>   System.Runtime.InteropServices.dll
>   System.Runtime.Loader.dll
>   System.Runtime.Numerics.dll
>   System.Runtime.Serialization.Formatters.dll
>   System.Runtime.Serialization.Json.dll
>   System.Runtime.Serialization.Primitives.dll
>   System.Runtime.Serialization.Xml.dll
>   System.Runtime.Serialization.dll
>   System.Runtime.dll
>   System.Security.AccessControl.dll
>   System.Security.Claims.dll
>   System.Security.Cryptography.Algorithms.dll
>   System.Security.Cryptography.Cng.dll
>   System.Security.Cryptography.Csp.dll
>   System.Security.Cryptography.Encoding.dll
>   System.Security.Cryptography.Native.OpenSsl.a
>   System.Security.Cryptography.Native.OpenSsl.so
>   System.Security.Cryptography.OpenSsl.dll
>   System.Security.Cryptography.Primitives.dll
>   System.Security.Cryptography.X509Certificates.dll
>   System.Security.Permissions.dll
>   System.Security.Principal.Windows.dll
>   System.Security.Principal.dll
>   System.Security.SecureString.dll
>   System.Security.dll
>   System.ServiceModel.Web.dll
>   System.ServiceProcess.ServiceController.dll
>   System.ServiceProcess.dll
>   System.Text.Encoding.Extensions.dll
>   System.Text.Encoding.dll
>   System.Text.Encodings.Web.dll
>   System.Text.RegularExpressions.dll
>   System.Threading.AccessControl.dll
>   System.Threading.Overlapped.dll
>   System.Threading.Tasks.Dataflow.dll
>   System.Threading.Tasks.Extensions.dll
>   System.Threading.Tasks.Parallel.dll
>   System.Threading.Tasks.dll
>   System.Threading.Thread.dll
>   System.Threading.ThreadPool.dll
>   System.Threading.Timer.dll
>   System.Threading.dll
>   System.Transactions.Local.dll
>   System.Transactions.dll
>   System.ValueTuple.dll
>   System.Web.HttpUtility.dll
>   System.Web.dll
>   System.Windows.dll
>   System.Xml.Linq.dll
>   System.Xml.ReaderWriter.dll
>   System.Xml.Serialization.dll
>   System.Xml.XDocument.dll
>   System.Xml.XPath.XDocument.dll
>   System.Xml.XPath.dll
>   System.Xml.XmlDocument.dll
>   System.Xml.XmlSerializer.dll
>   System.Xml.dll
>   System.dll
>   WindowsBase.dll
>   config.json
>   config.mainnet.json
>   config.testnet.json
>   createdump
>   libclrjit.so
>   libcoreclr.so
>   libcoreclrtraceptprovider.so
>   libdbgshim.so
>   libe_sqlite3.so
>   libhostfxr.so
>   libhostpolicy.so
>   libmscordaccore.so
>   libmscordbi.so
>   libsos.so
>   libsosplugin.so
>   mscorlib.dll
>   neo-cli
>   neo-cli.deps.json
>   neo-cli.dll
>   neo-cli.runtimeconfig.json
>   netstandard.dll
>   protocol.json
>   protocol.mainnet.json
>   protocol.testnet.json

I start neo-cli with
```
cd /home/neo/data
/home/neo/neo-cli/neo-cli  --rpc --log 
```
And no place in filesystem I see logs, or log folder. 
```
cat /home/neo/neoc-cli/Plugins/ApplicationLogs/config.json
{
  "PluginConfiguration": {
    "Path": "ApplicationLogs_{0}"
  }
}
```
Can you please tell where my logs are?

**Comment by ksemaev** [comment]
It appeared it data finaly, but has some strange stuff in the beginnig:

> _�� o�
> �
> [<�m�I"� �`�87"q���{"txid":"0xc4ff0271227f37389a601d9f200e00b72249896da23c5b000a00141fe40aea6f","executions":[{"trigger":"Application","contract":"0xebf0b1621d02c8078e6d501c95f306bee7bc3096","vmstate":"HALT","gas_consumed":"6.311","stack":[{"type":"Integer","value":"1"}],"notifications":[{"contract":"0xada839286d23cdfb42eb556461b9382d02b6e12f","state":{"type":"Array","value":[{"type":"ByteArray","value":"636f6e74726163745f7472616e73666572"},{"type":"ByteArray","value":"2fe1b6022d38b9616455eb42fbcd236d2839a8ad"},{"type":"ByteArray","value":"bf3efc76469b78e14dd1c0c2d454dff03e595daa"},{"type":"ByteArray","value":"465458"},{"type":"Integer","value":"5000000"}]}},{"contract":"0xada839286d23cdfb42eb556461b9382d02b6e12f","state":{"type":"Array","value":[{"type":"ByteArray","value":"766572696679"},{"type":"ByteArray","value":"bf3efc76469b78e14dd1c0c2d454dff03e595daa"},{"type":"Integer","value":"12921"}]}}]}]}

What are those strange symbols ^ ?

**Comment by belane** [comment]
It seems that the ApplicationLogs plugin is not in the right place, it should be copied to the Plugins folder.
Can you confirm that you have the following folder structure?
```
./Plugins/ApplicationLogs.dll
./Plugins/ApplicationsLogs/config.json
```
Once running, the plugin saves everything in a database inside "ApplicationLogs_00746E41" folder (if you have not changed the path in the configuration file).

iirc you can check the logs using the rpc `getapplicationlog` command.

**Comment by ksemaev** [comment]
TY, found it
