### ISSUE TITLE
Application logs plugin breakes neo-cli after upgrading to v2.10.3

### ISSUE THREAD

**Issue by ksemaev** [neo-project/neo-plugins#124]
Neo-cli just get stuck after upgrade. For it to work I had to remove the contents of `ApplicationLogs_00746E41/`

Please fix it

**Comment by superboyiii** [comment]
Hi, ksemaev, it works well on mine. Now seed nodes is crowded for connection, maybe you'll see "endpoint is not connected" from Akka exception. Never mind, just wait several seconds and it will start sync.
![image](https://user-images.githubusercontent.com/38493437/63161674-3d9c9000-c053-11e9-8ef7-9eb0306dfcda.png)

**Comment by superboyiii** [comment]
![image](https://user-images.githubusercontent.com/38493437/63161852-aab02580-c053-11e9-8209-70badb983afe.png)

**Comment by ksemaev** [comment]
I'm not sure if it's fair to compare Windows and Linix behaviours here. For me it crashes on ubuntu 18.04. Neo-cli just doesn't open ports, no info in logs. I've waited for an hour. If I delete the log folder content - it starts to work immediately

**Comment by shargon** [comment]
do you receive any exception?

**Comment by superboyiii** [comment]
Works well on my Ubuntu16.04, not sure if is there any problem on Ubuntu 18.04.
![778b6918e8d47098561f1ff91be78a2](https://user-images.githubusercontent.com/38493437/63211929-9b52da00-c130-11e9-806d-ed5d6bbf8a22.png)
![4b2c7f75baca74c389c241283642599](https://user-images.githubusercontent.com/38493437/63211931-a1e15180-c130-11e9-92d0-1f4658307d9b.png)
![e2a0d48d5b6e4ed6fefaf9ab04bcf38](https://user-images.githubusercontent.com/38493437/63211933-a443ab80-c130-11e9-8765-aa731c3d072a.png)

**Comment by lock9** [comment]
Hello @ksemaev  and  @superboyiii, can we close this?
@ksemaev I'm sorry for your issue, we will improve our release process to ensure this problem does not happen in the future.

**Comment by ksemaev** [comment]
Let's close, we'll see if it returnes
