### ISSUE TITLE
Export block makes extremely high cost of memory which usually cause system killed on Linux.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-plugins#129]
Export block makes extremely high cost of memory which usually cause system killed on Linux.
On mainnet export, our server which has 16G memory, is only able to hold on  about 2 million blocks' export. After that, it's been killed by ubuntu. Here's the line graph. I think ImportBlocks plugin is necessary to improve algorithm for export.
![image](https://user-images.githubusercontent.com/38493437/63504713-b2187880-c504-11e9-9bee-fbb731826260.png)

**Comment by shargon** [comment]
Thanks for this tests @superboyiii , this will helps to find performance issues

**Comment by lock9** [comment]
@superboyiii Hi! Is this solved?

**Comment by shargon** [comment]
@superboyiii we have the same issue with import?

**Comment by superboyiii** [comment]
@shargon No, it's because of that exporting block will write data straightly into memory which will cause overflow if your memory isn't large enough. But ```Import``` doesn't have this mechanism.

**Comment by shargon** [comment]
I think that the problem is here

https://github.com/neo-project/neo-plugins/blob/1c91346338c78537bec2760adfb363f3eb1619f5/ImportBlocks/ImportBlocks.cs#L84

Snapshot is a cache, and these blocks still on memory until the snapshot is disposed.

**Comment by shargon** [comment]
@superboyiii could you told Tom to make a Pull request? also if he can join the two logics will be great!

https://github.com/neo-project/neo-plugins/blob/1c91346338c78537bec2760adfb363f3eb1619f5/ImportBlocks/ImportBlocks.cs#L63

**Comment by shargon** [comment]
I see that is already done! :) 
https://github.com/neo-project/neo-plugins/issues/135

**Comment by KickSeason** [comment]
Will do
