### ISSUE TITLE
How do we compile the plugin to .dll files?

### ISSUE THREAD

**Issue by skinderis** [neo-project/neo-plugins#15]
I want to use **RpcSecurity** neo-plugin, but seems that in release compiled plugin is old yet (it's called **RpcDisabled**), and I need the new one (**RpcSecurity**).

There is no docs or Wiki for that, could please someone help me with that? Thank you!
@erikzhang

**Comment by skinderis** [comment]
@belane you intiated that update, maybe you could help me? I want to integrate this plugin into neo-cli 2.9.0 version.

**Comment by belane** [comment]
You can download the repository and compile in Visual Studio or use `dotnet build .`

**Comment by erikzhang** [comment]
```
dotnet build
```

**Comment by skinderis** [comment]
For people who will face the problem below in the future. I was getting this kind of errors: 

> Build FAILED.
> 
> /usr/share/dotnet/sdk/2.1.402/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/usr/neo-python/neo-plugins/ApplicationLogs/ApplicationLogs.csproj]
> 


Added these lines to `.csproj` file and it built successfully:

```
  <PropertyGroup Condition="'$(OS)' != 'Windows_NT' AND '$(TargetFramework)'== 'net47'">
    <!-- Make .NET 4.7 reference assemblies available even on Linux -->
    <FrameworkPathOverride>$(NuGetPackageRoot)microsoft.targetingpack.netframework.v4.7/1.0.1/lib/net47/</FrameworkPathOverride>
    <!-- Make sure the additional feed is searched. -->
    <RestoreAdditionalProjectSources>https://dotnet.myget.org/F/dotnet-core/api/v3/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup Condition="'$(OS)' != 'Windows_NT' AND '$(TargetFramework)'== 'net47'">
      <!-- Make sure the reference assemblies are available -->
      <PackageReference Include="Microsoft.TargetingPack.NETFramework.v4.7"
                        Version="1.0.1" ExcludeAssets="All" PrivateAssets="All" />
  </ItemGroup>

```

**Comment by erikzhang** [comment]
You do not need to change `.csproj`:

```
dotnet build -c Release -f netcoreapp2.0
```

**Comment by shargon** [comment]
@erikzhang we can made releases for plugins too?
