### ISSUE TITLE
Applicationlog param verification fail

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-plugins#152]
Applied the latest Applicationlog Plugin on master branch.
Applicationlog Plugin responsed "Invalid params" when invoke a normal tx(I tried genesis tx and one ordinary tx).
![image](https://user-images.githubusercontent.com/38493437/70202828-d6b3fb80-1755-11ea-8ee4-72cfdb699d1b.png)
It breaks here:
![image](https://user-images.githubusercontent.com/38493437/70202831-e03d6380-1755-11ea-91dd-5af14aa65478.png)
In getBlock, it returns this tx normally.
![image](https://user-images.githubusercontent.com/38493437/70202846-ea5f6200-1755-11ea-8040-b29a3ec7bf55.png)

**Comment by erikzhang** [comment]
Please test #154. It should fix this issue.
