### ISSUE TITLE
Is it possible to make a plugin to open wallet via RPC?

### ISSUE THREAD

**Issue by skinderis** [neo-project/neo-plugins#16]
Hi, I am interested if it's possible to open wallet remotely? I mean to create a plugin which will accept RPC method to open and close wallet or to encrypt and decrypt it?

Thanks!

**Comment by erikzhang** [comment]
If we pass the `RpcServer` object to the plugin, it might be able to open or unlock the wallet.

**Comment by skinderis** [comment]
The problem is that I don't realy know C#, is there anyone that is interested in implementing the plugin and knows C#?

**Comment by belane** [comment]
Sorry but is not in my near future roadmap, I'll take your suggestion later.
Meanwhile you can specify your wallet on settings (https://github.com/neo-project/neo-cli/blob/master/neo-cli/config.json#L16) and use https and basic auth from RpcSecurity plugin to secure your RPC.

**Comment by erikzhang** [comment]
@skinderis Now you can open wallet from plugin. https://github.com/neo-project/neo/pull/421
