### ISSUE TITLE
Does fixed8 sort and ordering really works correctly?

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-plugins#27]
@belane, @shargon, @igormcoelho, @erikzhang and @jsolman, I just wonder if there is any problem in the way that C# sort/order the fixed8 class. 

Here is the definition of this struct/class:
https://github.com/neo-project/neo/blob/c64748ecbac3baeb8045b16af0d518398a6ced24/neo/Fixed8.cs

Here is a normal sorting with `NetworkFee` being this fixed8 object.
```cs
transactions = array.OrderByDescending(p => p.NetworkFee / p.Size).ThenByDescending(p => p.NetworkFee).Take(Settings.Default.MaxTransactionsPerBlock - 1);
```

I am not expert in C# abstract functions, but I believe that the sorting mechanism probably calls some of these virtual implemented function that contains `override`:  `public override bool Equals(object obj)` and `public override int GetHashCode()`
In the way it works it calls `public int CompareTo(Fixed8 other)`.

**Comment by belane** [comment]
This Order calls the `public int CompareTo(Fixed8 other)` that uses long type `public int CompareTo(Int64 value)`. Shouldn't be a problem, am I wrong?

**Comment by vncoelho** [comment]
Hey, Belane,

As we discussed in the afternoon, I do not know. I think some of you guys will know...kkkkkkkkkkk
Anyway, it is easy to test in the Mainnet or even a Privatenet with some automatic txs. I gonna soon test it in a more automatic manner.

It is just a guess regarding the incidents of last week with some blocks with 21txs and mempool still full.

Anyway, let's check it out with time, I think there is no hurry in being sure about it...aehauhuea

**Comment by RavenXce** [comment]
> Hey, Belane,
> 
> As we discussed in the afternoon, I do not know. I think some of you guys will know...kkkkkkkkkkk
> Anyway, it is easy to test in the Mainnet or even a Privatenet with some automatic txs. I gonna soon test it in a more automatic manner.
> 
> It is just a guess regarding the incidents of last week with some blocks with 20txs (1 miner plus 20 free) and indications that mempool should contain more txs with fees.
> 
> Anyway, let's check it out with time, I think there is no hurry in being sure about it...aehauhuea

> It is just a guess regarding the incidents of last week with some blocks with 20txs (1 miner plus 20 free) and indications that mempool should contain more txs with fees.

We noticed that for a long time already, and the consensus was that some txns don't ever reach the consensus node due to other reasons (like large mempool causing performance/network issues). I noticed it still happening after 2.9.0 unfortunately.. but I can't figure out why still.

**Comment by vncoelho** [comment]
let's move forward.
We gonna find it.

This tests that Erik implemented almost cover all cases. In the future we can improve it a little bit.

With the new consensus improvements we gonna probably right another level! Let's go for it.
