### ISSUE TITLE
MaxFreeTransactionSize result in issues of ClaimTransaction

### ISSUE THREAD

**Issue by PeterLinX** [neo-project/neo-plugins#33]
https://github.com/neo-project/neo-plugins/blob/db04e756a64c149e86d117fe89879c72f319c7df/SimplePolicy/SimplePolicy/config.json#L5
It causes a problem for ClaimTransaction.  
For ClaimTransaction, people can't add network fee to it because it's set to zero, which means every ClaimTransaction is free transaction.(https://github.com/neo-project/neo/blob/7883e587a9448330d21669ebe748402871da3a50/neo/Network/P2P/Payloads/ClaimTransaction.cs#L16) Besides, the size of ClaimTransaction is usually larger than 1024. If we set MaxFreeTransactionSize to 1024, all ClaimTransaction will be influenced. If we make MaxFreeTransactionSize larger than 1024, then it's a meaningless configuration item. We get a paradox here.
Another thing is We can't prioritize ClaimTransaction anyway.
(https://github.com/neo-project/neo/blob/7883e587a9448330d21669ebe748402871da3a50/neo/Network/P2P/Payloads/Transaction.cs#L52)

**Comment by erikzhang** [comment]
@belane @igormcoelho @jsolman @localhuman @RavenXce @shargon @vncoelho

**Comment by shargon** [comment]
We should set the Max per type?

**Comment by erikzhang** [comment]
Maybe we can set the `ClaimTransaction` to always be high priority? Because `ClaimTransaction` needs to send neo first, and the transactions that send neo is limited by the priority mechanism, it will not cause an attack.

**Comment by vncoelho** [comment]
Peeeeeeeeeeeeeter Lin,
That is a great catch and attention.

I agree with you, set per type will be probably necessary.
I also agree with you, , that is a good observation.

Maybe we should make sure that any remark or additional spam info is inside the `Claim tx`, but I still do not know the best way.

Is it bad if `ClaimTransaction` is removed and embed it inside the Application Layer? Every time NEO's is sent we get that UTXO's and make the funds available under the ID of the current `tx hash`?

**Comment by shargon** [comment]
https://github.com/neo-project/neo/pull/510 not fix the issue, the solution should applied in the plugin

**Comment by igormcoelho** [comment]
I think should allow claim to surpass tx size limit, at least for now. Then we think of better ways to claim with few bytes.

**Comment by igormcoelho** [comment]
Congratulations guys, this is nice! :)
