### ISSUE TITLE
Access an opened wallet in RPC plugin

### ISSUE THREAD

**Issue by apisit** [neo-project/neo-plugins#36]
Is it possible to access an opened wallet in a RPC plugin?

**Comment by shargon** [comment]
Yes, for example this: https://github.com/neo-project/neo/blob/c16475e7c11c6e1fcf81a062a825ee5e30089daa/neo/Network/RPC/RpcServer.cs#L165

You have examples of other calls here: https://github.com/neo-project/neo/wiki/API-Reference

**Comment by apisit** [comment]
Thanks @shargon 
perhaps I wasn't so clear. I am making a new plugin to add another RPC method and I want to access the wallet property to do something with it. Looks like it's a private property.

The given link, isn't it inside a neo-cli itself? 

Can we pass it to the plugin or make the `wallet` property public? 
https://github.com/neo-project/neo/blob/c16475e7c11c6e1fcf81a062a825ee5e30089daa/neo/Network/RPC/RpcServer.cs#L641

**Comment by shargon** [comment]
Sorry for my misunderstanding,

With this change https://github.com/neo-project/neo/pull/536 and this code you can do it :)

```csharp
  public static Wallet GetWallet(this HttpContextBase context)
    {
        return (Wallet)context.Items["Wallet"];
    }
```
