### ISSUE TITLE
Simplepolicy 2.9.4 error

### ISSUE THREAD

**Issue by ghost** [neo-project/neo-plugins#51]
Neo.Plugins.SimplePolicyPlugin' from assembly 'SimplePolicy, Version=2.9.4.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by vncoelho** [comment]
Hi @freshboychen, I remembered that I got this error but was something related to combination of codes that I was using.
Can you give more details?

**Comment by vncoelho** [comment]
@ghost, I gonna leaved this one closed until more details are provided, it was probably an error due to different versions being used as .dlls of a client. But fell free to reopen it, maybe it can be some minor thing that we can track or fix.
