### ISSUE TITLE
ApplicationLogs Plugin doesn't work while using offline package syncing

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-plugins#69]
Recently, I find ApplicationLogs Plugin doesn't work while offline package syncing. This situation doesn't appear among official seed nodes but normal external nodes could always meet this issue.
I found that the leveldb format is also different between these two kinds of nodes, centOS is *.sst but Ubuntu is *.ldb. Not sure if it's the reason related to this issue. The normal one is on CentOS and the unnormal one is on Ubuntu. Seems they're using different version of LevelDB.

The phenomenon, for example, could be --> The offline sync package is at the height of 3400000+, when the sync is completed, find a random transaction at a lower height, such as finding an NEP-5 transaction at the height of 2800000, like f869e2ccaa916873ea4f648b8e16751f7c37963b97113e36b7da7628a2b06794
![image](https://user-images.githubusercontent.com/38493437/54656123-6568e580-4aff-11e9-9881-f91c8fba4814.png)

The result of rpc post is "Unknown transaction" on external nodes. 
![image](https://user-images.githubusercontent.com/38493437/54656237-d6100200-4aff-11e9-98e7-157d4c55c433.png)

But seed nodes on Unbuntu return the correct result.
![image](https://user-images.githubusercontent.com/38493437/54656317-140d2600-4b00-11e9-8307-2c4eb9fe4b5e.png)

**Comment by superboyiii** [comment]
Additional word, it syncs well above the height of offline package. But the previous logs don't exist.

**Comment by superboyiii** [comment]
During my test these days, I find it's not OS's business. ApplicationLogs seems only work on seed nodes when using offline package..

**Comment by superboyiii** [comment]
More and more developers feed back about the same situation.

**Comment by jsolman** [comment]
Which version of the plugin are you using? Are you using the latest version the Commit from this PR? https://github.com/neo-project/neo-plugins/pull/62

**Comment by jsolman** [comment]
Or are you using the version that was in the release from here: https://github.com/neo-project/neo-plugins/releases/tag/v2.10.0 ?

**Comment by KickSeason** [comment]
#62 fix this
