### ISSUE TITLE
Bug in the recovery request hangling

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo-plugins#722]
There are 4 nodes and one of them (node 1) is down.
Another 3 have problems (message lost, 2 of the nodes changed view, another one didn't).
Let's say node 0 is behind. Turns out, the only node which can response to the recovery request is node 1 which is down.
https://github.com/neo-project/neo-modules/blob/master/src/DBFTPlugin/Consensus/ConsensusService.OnMessage.cs#L290

I believe, `f+1` should be used.

**Comment by Liaojinghui** [comment]
I don't get. With 4 nodes, one down, and rest also have issue? Isn't this break the assumption of dbft?

**Comment by fyrchik** [comment]
No, it doesn't, even with 3 nodes it should _eventually_ accept some block. In the situation I described, we have a deadlock.

**Comment by Liaojinghui** [comment]
>There are 4 nodes and one of them (node 1) is down.
Another 3 have problems (message lost, 2 of the nodes changed view, another one didn't).

If we assume one node is down, then the rest of the nodes should not have any message lost assumptions. Malicious node, no respond node, message lost node are all Byzantine nodes, when you have 4 nodes network, at most 1 can be Byzantine node. It is reasonable to change f to f+1, which makes sense, but not in a deadlock way.

**Comment by fyrchik** [comment]
Ok, I agree that it breaks assumptions. It is just that loss of a _single_ message shouldn't lead to inability to proceed. We can reasonably expect some messages to be lost under heavy load. The fix is quite simple IMO and doesn't punish us a lot, because recovery requests are rare.

**Comment by ZhangTao1596** [comment]
If there are 2 failed nodes, this is against the BFT assumption.
If there is a commited node, we have this https://github.com/neo-project/neo-modules/blob/b9eaa9d84992ce92316f30d1e5e9372914582c49/src/DBFTPlugin/Consensus/ConsensusService.cs#L175-L180

**Comment by vncoelho** [comment]
@ZhangTao1596, the assumption of a an honest node consider that it can delay (at least) or messages can be lost.

In the example that was given it was node 0.

While node 1 is the only byzantine.

**Comment by vncoelho** [comment]
`f to f+1 or even 2f+1, which makes sense to me, but not in a deadlock way.`

In a discussion with @igormcoelho yesterday, he highlighted the same sentence you wrote here.

**Comment by vncoelho** [comment]
@ZhangTao1596, the mechanism you pointed out is nice. I am glad you remembered it. This is quite useful for several occasions.
However, when we implemented this `context.CountFailed` it considered the last received message from last round or current round.

In the aforementioned case, node 0 would not be considered failed by other nodes because they received messages from it.

**Comment by ZhangTao1596** [comment]
Since this makes neo more robust. I'm ok with it.
