### ISSUE TITLE
Check tx that contains a certain syscall in plugin.

### ISSUE THREAD

**Issue by apisit** [neo-project/neo-plugins#83]
I'm writing a plugin to catch a transaction with a certain syscall. particularly, [Neo.Contract.Create](https://github.com/neo-project/neo/blob/d18990acfd1c932d101437c3973d91ac8dde3e02/neo/SmartContract/NeoService.cs#L80) to log all deployed contracts.

I am aware that `ApplicationExecutionResult` contains `InteropInterface` in the stack. 

sample contract deploy event from `getapplicationlog` rpc 
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "txid": "0x1fc9e3728b5a3d831bea9aa90fe463c6982039042e0302a7f8a86611660bf964",
    "executions": [
      {
        "trigger": "Application",
        "contract": "0x63c6111e93885ff24710426e167b7e87aa600d10",
        "vmstate": "HALT, BREAK",
        "gas_consumed": "500",
        "stack": [
          {
            "type": "InteropInterface"
          }
        ],
        "notifications": []
      }
    ]
  }
}
```
my question is, How can I check it? 
Can anyone shed some light on how to achieve this?

**Comment by shargon** [comment]
You need to convert this `InteropInterface` to `ContractState` using `GetInterface` method.
The problem is when you be able to do that, currently i think that we don't have plugins for invocations, so is more difficult to detect. In the past, I proposed to create events for made this kind of this easier (https://github.com/neo-project/neo/issues/679).

**Comment by vncoelho** [comment]
@hal0x2328 has been also working on a debugging plugin: https://github.com/hal0x2328/LocalDebugger
I believe he might give us a light on this here.

**Comment by hal0x2328** [comment]
> @hal0x2328 has been also working on a debugging plugin: https://github.com/hal0x2328/LocalDebugger
> I believe he might give us a light on this here.

Yes, I don't see any reason I couldn't add this to my debugger plugin's StepInto implementation, just test if the next opcode == SYSCALL, then read the name from the script buffer to compare against, then retrieve the contract creation arguments from the stack if it matches.

 But it sounds like @apisit wants something less interactive than the full debugger to just log the contract details, so maybe he can use it as a basis for his plugin and strip most of the code to make a new plugin to do just what is needed.

**Comment by vncoelho** [comment]
By the way, I think that this plugin of @hal0x2328 should come to this repo.

**Comment by apisit** [comment]
Thanks everyone! 

I am able to get `EvaluationStack` result now.

```csharp

                InvocationTransaction invTx = (InvocationTransaction)tx;
                ApplicationEngine _engine = ApplicationEngine.Run(invTx.Script);
                JArray list = new JArray();
                string nextInstruction = _engine.CurrentContext.NextInstruction.ToString();
                if (nextInstruction != "SYSCALL") {
                    return null;
                }
                for (var i = _engine.CurrentContext.EvaluationStack.GetEnumerator(); i.MoveNext();)
                {
                    StackItem item = i.Current;
                    var j = new JObject();
                    j["type"] = item.GetType().Name;
                    j["item"] = item.GetByteArray().ToHexString();
                    list.Add(j);
                }

                return list;
```

@hal0x2328 I  read your plugin code and it seems like to be able to get the name, I need `NeoDisassembler `?

**Comment by hal0x2328** [comment]
If the next instruction is the SYSCALL why do you need the current instruction? You want to read the bytes after the SYSCALL instruction pointer - first an integer (length of the string) then read that many many bytes. So if you don't want to load the entire NeoDisassembler class you can just create a BinaryReader with a MemoryStream created from the script bytes and do ```var name  = reader.ReadBytes((int)reader.ReadVarInt((ulong)max))``` starting at the offset after the syscall.

**Comment by apisit** [comment]
Thanks @hal0x2328 
finally figured it out. did exactly that then I just `.Pop` from the `EvaluationStack` to get a smart contract's script and `.ToScriptHash()`.
just what I needed, now I have a plugin in to log all deployed contracts 💃
