### ISSUE TITLE
ApplicationLogs returns absolutely different result when in v2.10.0 and v2.10.1

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-plugins#89]
[ApplicationLogsResult -EN.txt](https://github.com/neo-project/neo-plugins/files/3107010/ApplicationLogsResult.-EN.txt)

It's on mainnet using seed node6 and seed node10 for invoking ApplicationLogs which are in versions of 2.10.0 and 2.10.1.

**Comment by superboyiii** [comment]
The txid is 275bb3c080884b41afa14a3f6db2581fa0a54e25d35a66ce99859925a08de812

**Comment by igormcoelho** [comment]
Good catch @superboyiii , we are trying to diagnose the precise change which is causing this, before nodes actually start using this version.

**Comment by superboyiii** [comment]
Thanks a lot.

**Comment by superboyiii** [comment]
This issue seems already be solved. Let me close.
