### ISSUE TITLE
“getnep5transfers” doesn't get expected result on mainnet

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-plugins#93]
I made a test for NEP5Tracker on mainnet yesterday. getnep5balances worked well as expected, but getnep5transfers didn't work until I sync to the latest height. However, it works well on my privatenet. The only difference is the version of consensus. Is there any possibility of the VM difference between 2.4.0 and 2.4.2?
The mainnet is 2.9.4 and my privatenet is 2.10.2 preview3. So in order to prove that, we also applied it on testnet since the consensus version is 2.10.1+. The result is the same as my privatenet. It worked as expected. But it still doesn't work on mainnet.

For example, on mainnet, I choose a random address "AZsvkf5fopsUvfMbsHfx9qKmwswtgdsgZv" which has a transaction on height of "1768508".
The txid is "0f2896032f3ad8614ce50e87b0db17a028bba976d25715f517c9201de82ee7d5".
![image](https://user-images.githubusercontent.com/38493437/57512567-9070f800-733e-11e9-87b5-6feefc56ec5e.png)
Then I use getnep5transfers to get all nep5 transaction history. But the result is like this.
![image](https://user-images.githubusercontent.com/38493437/57512587-9ff04100-733e-11e9-9cb4-994243e0efa9.png)
Nothing is there.

**Comment by shargon** [comment]
Do you know if this contract create the `transfer` notification?
https://github.com/neo-project/neo-plugins/blob/master/RpcNep5Tracker/RpcNep5Tracker.cs#L127

**Comment by superboyiii** [comment]
I don't know if it create the transfer notification. But on my privatenet, when I use 2.9.4 to make consensus, and install NEP5Tracker on external node which is in 2.10.2 preview3, I could still meet this problem. My nep-5 contract which I deployed on it must create the transfer notification. And during my mainnet test, **getnep5transfers ** has this issue on all contracts, this is only one of them. @shargon

**Comment by vncoelho** [comment]
Hi @superboyiii, how is it going?
If it is still a problem verified let's fix this asap because it will be important for both 2.x and 3.0.

**Comment by jsolman** [comment]
It only returns the time for the transfers in the last 7 days, you have to include additional parameters to get history for different interval...

**Comment by jsolman** [comment]
I think I answered this before on a comment made on the plugin PR also. Feel free to open it again if you verify you are using the api appropriately and still don’t see the transfer history, but it should work if you include the correct time range in the query.

**Comment by vncoelho** [comment]
Thanks, @jsolman.

   Could you give more details of this parameter? I will make sure to include a description in the code for making it an easy adjustment in the future.

**Comment by jsolman** [comment]
The parameter is easy to find in the code in the GetNep5Transfers function; first param: script hash, second param: startTime, third param endTime
