### ISSUE TITLE
Installed neo-plugins via Cli. But plugins not loaded after cli start

### ISSUE THREAD

**Issue by ebrahimasifismail** [neo-project/neo-plugins#95]
neo-cli 2.10.1.0, ubuntu 18.04
started node using ./neo-cli --rpc --log
install <plugin-name>
restarted the cli
but on plugins command "no plugins loaded"
plugin Files downloaded in /neo-cli/neo-cli/bin/Release/netcoreapp2.1/linux-x64/Plugins

**Comment by ebrahimasifismail** [comment]
installed ApplicationLog via neo-cli.. Then restarted the client. But json rpc api call return "method not found"

>>>curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","method": "getapplicationlog","params": ["0xff488264c1abf9f5c3c17ed8071f6dd3cd809b25797a43af49316490ded8fb07"],"id": 1}' http://140.82.40.51:10332/

{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"Method not found"}}

**Comment by ebrahimasifismail** [comment]
also plugins command in neo-cli returns no loaded plugins

**Comment by ebrahimasifismail** [comment]
installed ApplicationLog via neo-cli.. Then restarted the client. But json rpc api call return "method not found"

>>>curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","method": "getapplicationlog","params": ["0xff488264c1abf9f5c3c17ed8071f6dd3cd809b25797a43af49316490ded8fb07"],"id": 1}' http://x.x.x.x:10332/

{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"Method not found"}}

**Comment by shargon** [comment]
Fixed on https://github.com/neo-project/neo-cli/pull/360
